In [7]:
# Importar pandas
import pandas as pd

In [8]:
#TEST_CELL
!python --version
print('Pandas', pd.__version__)

Python 3.12.12
Pandas 2.2.2

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
# Read the the titanic csv file into the the titanic data frame
titanic = pd.read_csv('titanic.csv')
titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
titanic.loc[:,"Name"]

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [12]:
#TEST_CELL
### Write your code here ###
titanic.loc[:,"Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [13]:
#TEST_CELL
### Write your code here ###
titanic.loc[:,"Cabin"]

0       NaN
1       C85
2       NaN
3      C123
4       NaN
       ...
886     NaN
887     B42
888     NaN
889    C148
890     NaN
Name: Cabin, Length: 891, dtype: object

In [14]:
#TEST_CELL
### Write your code here ###
titanic.loc[:,"Embarked"]

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Hints</b></font>
</summary>

* In this exercise you can explore manually using functions like **`.describe`** or **`.info`** to identify variables with missing values but you have to use  **`.isnull().any()`** to do it in coding.

In [46]:
# GRADED VARIABLE: variables_with_missing_values:

### Write your code here ###  (~ 1 line of code)
variables_with_missing_values = titanic.columns[titanic.isnull().any()].tolist()

In [53]:
# GRADED VARIABLE: categorical_variables (list):
categorical_variables = titanic.select_dtypes(exclude=["number"]).columns

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [17]:
# GRADED VARIABLE: boarding_counts:

boarding_counts = titanic["Embarked"].value_counts()

boarding_counts

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [18]:
averages_by_group = titanic.select_dtypes(include='number')
averages_by_group

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [19]:
# GRADED VARIABLE: boarding_counts:

averages_by_group = titanic.select_dtypes(include="number").groupby("Survived").mean()
averages_by_group  # Replace the empty DataFrame with the correct answer.

          PassengerId    Pclass        Age     SibSp     Parch       Fare
Survived
0          447.016393  2.531876  30.626179  0.553734  0.329690  22.117887
1          444.368421  1.950292  28.343690  0.473684  0.464912  48.395408

In [20]:
##TEST_CELL
averages_by_group > 10

          PassengerId  Pclass   Age  SibSp  Parch  Fare
Survived
0                True   False  True  False  False  True
1                True   False  True  False  False  True

In [21]:
# GRADED VARIABLE: numeric_survival:

numeric_survival = titanic[titanic["Survived"] == 1].mean(numeric_only=True).drop(["Survived"])
#numeric_survival = pd.Series() # Replace the empty Series object with the correct answer.

In [22]:
#TEST_CELL
numeric_survival.astype(int)

PassengerId    444
Pclass           1
Age             28
SibSp            0
Parch            0
Fare            48
dtype: int64

**Expected output:**
```python
PassengerId    444
Pclass           1
Age             28
SibSp            0
Parch            0
Fare            48
Name: 1, dtype: int64
```

In [23]:
# GRADED VARIABLE: survival_sex:

survival_sex = titanic.groupby('Sex')[['Survived']].mean()
#survival_sex = pd.DataFrame() # Reemplace el DataFrame vacío por la respuesta correcta.

In [24]:
#TEST_CELL
(survival_sex * 100).astype(int)

        Survived
Sex
female        74
male          18

**Expected output:**

```python
	    Survived
Sex
female  74
male    18
```

In [25]:
# GRADED VARIABLE: non_null_rows_titanic

non_null_rows_titanic = titanic.dropna()
#non_null_rows_titanic = pd.DataFrame() # Reemplace el DataFrame vacío por la respuesta correcta.

In [26]:
#TEST_CELL
non_null_rows_titanic.count()

PassengerId    183
Survived       183
Pclass         183
Name           183
Sex            183
Age            183
SibSp          183
Parch          183
Ticket         183
Fare           183
Cabin          183
Embarked       183
dtype: int64

**Expected output:**

```python
PassengerId    183
Survived       183
Pclass         183
Name           183
Sex            183
Age            183
SibSp          183
Parch          183
Ticket         183
Fare           183
Cabin          183
Embarked       183
dtype: int64
```

### **3.2. Removing columns with missing values**

In [38]:
# GRADED VARIABLE: non_null_cols_titanic

non_null_cols_titanic = titanic.dropna(axis=1)
#non_null_cols_titanic = pd.DataFrame() # Replace the empty DataFrame with the correct answer.

In [39]:
#TEST_CELL
non_null_cols_titanic.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
SibSp          891
Parch          891
Ticket         891
Fare           891
dtype: int64

**Expected output:**

```python
PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
SibSp          891
Parch          891
Ticket         891
Fare           891
dtype: int64
```

In [29]:
# GRADED VARIABLE: full_rows

full_rows = non_null_rows_titanic.size
#full_rows = None
### End of code ###

full_rows

2196

In [40]:
# GRADED VARIABLE: full_cols

full_cols = non_null_cols_titanic.size
#full_cols = None
### End of code ###

full_cols

8019

In [31]:
### DO NOT MODIFY THIS CELL
# Create copy of titanic
imputed_cols_titanic = titanic.copy()

In [32]:
# GRADED VARIABLE: age_mean

age_mean = titanic['Age'].mean()
#age_mean = None

In [33]:
# GRADED VARIABLE: imputed_cols_titanic['Age']

### Write your code here ###  (~ 1 line of code)
imputed_cols_titanic['Age'] = titanic['Age'].fillna(age_mean)

In [34]:
#TEST_CELL
# Verify that there are no missing values:
imputed_cols_titanic['Age'].isna().sum()

np.int64(0)

In [35]:
# GRADED VARIABLE: imputed_cols_titanic['Family']

imputed_cols_titanic['Family'] = imputed_cols_titanic['SibSp'] + imputed_cols_titanic['Parch']
#imputed_cols_titanic['Family'] = 0

In [36]:
#TEST_CELL
list(imputed_cols_titanic['Family'].head(10))

[1, 1, 0, 1, 0, 0, 0, 4, 2, 1]

The output of the above cell should be:
```python
0    1
1    1
2    0
3    1
4    0
5    0
6    0
7    4
8    2
9    1
Name: Family, dtype: int64
```

In [37]:
#TEST_CELL
import numpy as np
print(np.array(imputed_cols_titanic['Family']).sum())

806

The output of the above cell should be:
```python
806
```